version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15
default: &default
  working_directory: ~/vue_s3_app
  docker:
    - image: cimg/node:18.1.0-browsers

jobs:
  build_and_test:
    <<: *default
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [dist]
  deploy-to-s3:
    machine:
      image: unbutu:latest
      docker_layer_caching: true
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::459716160169:role/Terraform-BackendS3BackendRole
          aws-region: ap-northeast-1

      - name: Upload
          run: aws s3 cp --recursive ./dist s3://vue-s3-web
workflows:
  version: 2
  build_and_run_test:
    jobs:
      - build_and_test
      - deploy-to-s3:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
