version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

default: &default
  working_directory: ~/vue_s3_app
  docker:
    - image: cimg/node:18.1.0-browsers

permissions:
  id-token: write
  contents: read

jobs:
  build_and_test:
    <<: *default
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy-to-s3:
    executor: aws-cli/default
    working_directory: ~/vue_s3_app
    environment:
      AWS_REGION_NAME: ap-northeast-1
    parameters:
      resource:
        type: string
      env:
        type: string
      destination:
        type: string
    steps:
      - checkout
      - run: pwd && ls -la
      - attach_workspace:
          at: ~/vue_s3_app
      - aws-cli/install
      - aws-cli/setup:
          role-arn: "arn:aws:iam::${IAM_ID_TEST}:role/${IAM_ROLE_TEST}"
          role-session-name: "circleci-oidc"
      # - run: aws sts get-caller-identity
      - run: pwd && ls -la
      - run: ls dist -la -R
      - run:
          name: Upload dist to AWS.S3 <<parameters.destination>>
          command: |
            AWS_S3_PATHS=$(aws s3 ls)
            SUFFIX=${AWS_S3_PATHS##*<<parameters.env>>-marketing-lp-front}
            echo $SUFFIX
            echo $AWS_REGION_NAME
            aws s3 sync --region $AWS_REGION_NAME ~/vue_s3_app/<<parameters.resource>> s3://<<parameters.env>>-marketing-lp-front${SUFFIX}/<<parameters.destination>> 

workflows:
  version: 2
  deploy_to_stg:
    jobs:
      - build_and_test
      - deploy-to-s3:
          context: deploy_mfx_marketing_lp
          env: test
          resource: dist/
          destination: MSAD/app
          requires:
            - build_and_test
          filters:
            branches:
              only: master

  # deploy_to_prod:
  #   jobs:
  #     - build_and_test:
  #         context: deploy_mfx_marketing_lp
  #     - deploy-to-s3:
  #         context: deploy_mfx_marketing_lp
  #         filters:
  #           tags:
  #             only: /release-.*/
  #           branches:
  #             ignore: /.*/
