version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
default: &default
  working_directory: ~/vue_s3_app
  docker:
    - image: cimg/node:18.1.0-browsers

jobs:
  build_and_test:
    <<: *default
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [dist]

  deploy-to-s3:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/vue_s3_app
      - aws-cli/install
      - aws-cli/setup:
          profile-name: vue s3 web
          role-arn: arn:aws:iam::459716160169:role/circleci
      - run: aws sts get-caller-identity
      - run:
          name: Upload
          command: |
            aws s3 cp --recursive ./dist s3://vue-s3-web-s3-backend --region "ap-northeast-1"

workflows:
  version: 2
  build_and_run_test:
    jobs:
      - build_and_test:
          context: common_context
      - deploy-to-s3:
          context: common_context
          requires:
            - build_and_test
          filters:
            branches:
              only: master
