version: 2.1
default: &default
  working_directory: /vue_s3_app
  docker:
    - image: circleci/node:8.11.2

jobs:
  build_and_test:
    <<: *default
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [dist]

workflows:
  version: 2
  build_and_run_test:
    jobs:
      - build_and_test
