version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

default: &default
  working_directory: ~/vue_s3_app
  docker:
    - image: cimg/node:18.1.0-browsers

permissions:
  id-token: write
  contents: read

jobs:
  build_and_test:
    <<: *default
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy-to-s3:
    executor: aws-cli/default
    working_directory: ~/vue_s3_app
    steps:
      - checkout
      - attach_workspace:
          at: ~/vue_s3_app/dist
      - aws-cli/install
      - run:
          name: Assume role
          command: |
            aws_sts_credentials=$(aws sts assume-role-with-web-identity \
                --role-arn arn:aws:iam::459716160169:role/circleci \
                --web-identity-token ${CIRCLE_OIDC_TOKEN} \
                --role-session-name "circleci-oidc" \
                --duration-seconds 900 \
                --query "Credentials" \
                --output "json")
              echo export AWS_ACCESS_KEY_ID="$(echo $aws_sts_credentials | jq -r '.AccessKeyId')" >> $BASH_ENV
              echo export AWS_SECRET_ACCESS_KEY="$(echo $aws_sts_credentials | jq -r '.SecretAccessKey')" >> $BASH_ENV
              echo export AWS_SESSION_TOKEN="$(echo $aws_sts_credentials | jq -r '.SessionToken')" >> $BASH_ENV
              source $BASH_ENV
      - run: aws sts get-caller-identity
      - run:
          name: Upload
          command: |
            aws s3 sync ~/vue_s3_app/dist s3://vue-s3-web-s3-backend --region "ap-northeast-1"

workflows:
  version: 2
  build_and_run_test:
    jobs:
      - build_and_test:
          context: common_context
      - deploy-to-s3:
          context: common_context
          requires:
            - build_and_test
          filters:
            branches:
              only: master
