version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15
default: &default
  working_directory: ~/vue_s3_app
  docker:
    - image: cimg/node:18.1.0-browsers

jobs:
  build_and_test:
    <<: *default
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: [dist]
  deploy-to-s3:
    name: Upload to AWS S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - checkout
      - attach_workspace:
          at: ~/vue_s3_app
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::459716160169:role/Terraform-BackendS3BackendRole
          aws-region: ap-northeast-1
      - name: Copyfile AWS credential from Test account
        run: |
          aws s3 sync ./dist s3://vue-s3-web
workflows:
  version: 2
  build_and_run_test:
    jobs:
      - build_and_test
      - deploy-to-s3:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
